# Generated by Django 4.1.3 on 2022-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='saturday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='sunday',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
