# Generated by Django 4.1.3 on 2022-11-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_meetings_saturday_meetings_sunday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='end_time',
            field=models.CharField(blank=True, default='00.00.00.000000-05:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_time',
            field=models.CharField(blank=True, default='00.00.00.000000-05:00', max_length=100),
        ),
    ]
